### PR TITLE
[WIP] grand simplification

### PR DESCRIPTION
**Pull request by o-**
That's as far as I got with #104 

I abandoned the heap and decided to store arrays on the ocaml heap. It's maybe conceptually not as nice but it saves a lot of loc

### CODE REVIEW

**Comment by gasche** [comment]
I am worried about dropping the heap, because I think that reasoning about it may matter in correctness proofs (it remains part of the machine state), and it's nicer if we can reason directly on the state as manipulated by the implementation. On the other hand, if we decide right now to not have any optimization of heap-allocation scenarios, then that's fine.

**Comment by o-** [comment]
tried to reply by mail. that didn't work

> I am worried about dropping the heap,

I agree. I'll try something else. The main problem is that allocating arrays in an expression makes eval have some side-effects (ie. growing the heap). I am not sure how to deal with it. We could
* make creating an array an instruction. This keeps eval pure, but is a bit ugly.
* have array as values as the result of the expression and then the assignment instruction creates the heap cell. Eval stays pure, but it's a bit tricky to get right and not have the array values escape to some unforeseen places.
* Argue that extending the heap is not an observable side-effect (since the fresh reference cannot have escaped) and allow it.

**Comment by mhyee** [comment]
The third option seems slightly better than the first. The second seems brittle.

**Comment by gasche** [comment]
I would think that the first plan is fine: `alloc x[n]` assigns a fresh array of `nil`s of size `n` to `x`.

**Comment by mhyee** [comment]
How would you write array literals? `alloc x[] = [1, 2, 3]`?

What if you wanted to use an array literal within an expression? Or do we want to forbid this?

Actually, if we use the third option, doesn't the array reference escape?
```
  call x = foo([1, 2, 3])
function foo(ref a)
  return a
````

So maybe we want to use the first option, and forbid arrays in expressions. This would be similar to how we handle calls: `call x = foo (...)`.

**Comment by gasche** [comment]
Your `alloc x[] = [...]` proposal seems fine to me.

Array literals todays are expressions but not simple expressions -- they cannot appear as argument of a function, for example, so the further issues you mention are already ruled out.

**Comment by aviralg** [comment]
If we allow side effects in expressions, what do we lose? Does it make it difficult to prove correctness?

**Comment by gasche** [comment]
I think that it does not introduce an essential difficulty, but it does make everything a bit heavier, in the implementation and in the proof, as expression-related functions (and reasonings) need to return a new updated heap.

**Comment by o-** [comment]
> but it does make everything a bit heavier,

yeah it was really painful in #110 and I think not worth pursuing after all...

I still find option 2 (have array as values as the result of the expression and then the assignment instruction creates the heap cell) the most attractive. But I don't know how to implement it :(

**Comment by o-** [comment]
So I am keeping this PR open to keep the discussion visible. But I think it's better to start from scratch. This PR is not good because it uses the ocaml heap. #110 is painfully dragging the heap around in eval and is doing too much anyways. Maybe it has to be done in steps. For example first remove const. Then reintroduce local vars. I don't know

**Comment by gasche** [comment]
Done in #121.

**Pull request closed without merging**
