### PR TITLE
code coverage

### PR DESCRIPTION
**Pull request by gasche**
Code coverage using [bisect_ppx](https://github.com/aantron/bisect_ppx/), because why not?

### CODE REVIEW

**Comment by mhyee** [comment]
Cool! Unfortunately, the Travis build is failing, could you fix that?

Once Travis is green, you can merge.

**Comment by gasche** [comment]
Travis fails because of a typo in the package name. Fixed.

Do we want [Coveralls.io](https://coveralls.io/) support?

**Comment by mhyee** [comment]
If you think you can do it in 30 min (or an arbitrary limit of your choice), sure.

**Comment by gasche** [comment]
I went ahead and merged. @o-, @mhyee, `bisect_ppx` is now an additional dependency of the project.

(I let got of the coveralls.io support, I didn't want to spend the time configuring the thing for now.)

**Pull request merged**
